import type { Metadata } from "next";
import "./globals.css";
import {Montserrat} from "next/font/google";
import Navbar from "./shared/components/navbar";

const montserrat = Montserrat({
  subsets : ["latin"],
  display : "swap",
  weight: ["100","200", "300", "500"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: React.ReactNode;
  isAuthenticated: boolean;
}

export default function RootLayout({
  children,
  isAuthenticated,
}: LayoutProps) {
  console.log(isAuthenticated);
  return (
    <html lang="en">
      <body className={montserrat.className}>
      {isAuthenticated ? <Navbar /> : null}
      {children}
      </body>
    </html>
  );
}
